import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Logo from '../components/Logo';
import { supabase } from '../lib/supabase';

export default function ResetPasswordPage(){
  const navigate=useNavigate(); const [ready,setReady]=useState(false); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [message,setMessage]=useState({type:'',text:'جاري التحقق من رابط الاستعادة...'}); const [busy,setBusy]=useState(false);
  useEffect(()=>{(async()=>{try{const hash=new URLSearchParams(window.location.hash.slice(1));const accessToken=hash.get('access_token');const refreshToken=hash.get('refresh_token');const type=hash.get('type');if(accessToken&&refreshToken){if(type&&type!=='recovery')throw new Error('هذا الرابط ليس رابط استعادة كلمة مرور صالحًا.');const {error}=await supabase.auth.setSession({access_token:accessToken,refresh_token:refreshToken});if(error)throw error;history.replaceState(null,document.title,window.location.pathname+window.location.search);}const {data}=await supabase.auth.getSession();if(!data.session)throw new Error('رابط الاستعادة غير صالح أو انتهت صلاحيته. اطلب رابط استعادة جديدًا.');setReady(true);setMessage({type:'',text:''});}catch(error){setMessage({type:'error',text:error.message});}})();},[]);
  const submit=async(e)=>{e.preventDefault();setMessage({type:'',text:''});if(password.length<6){setMessage({type:'error',text:'كلمة المرور يجب أن تكون 6 أحرف على الأقل.'});return;}if(password!==confirm){setMessage({type:'error',text:'كلمتا المرور غير متطابقتين.'});return;}setBusy(true);const {error}=await supabase.auth.updateUser({password});if(error){setBusy(false);setMessage({type:'error',text:error.message});return;}await supabase.auth.signOut();setReady(false);setMessage({type:'success',text:'تم تحديث كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول.'});setTimeout(()=>navigate('/login',{replace:true}),1800);};
  return <main className="auth-shell"><div className="auth-wrap reset"><div className="auth-top-logo"><Logo /></div><div className="auth-card" style={{padding:'36px 30px'}}><h1 style={{fontSize:25}}>إعادة تعيين كلمة المرور</h1><p className="auth-sub">افتح هذه الصفحة من رابط الاستعادة المرسل إلى بريدك، ثم اختر كلمة مرور جديدة.</p>{ready&&<form onSubmit={submit}><label>كلمة المرور الجديدة</label><input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/><label>تأكيد كلمة المرور</label><input type="password" minLength={6} value={confirm} onChange={e=>setConfirm(e.target.value)} required/><button className="auth-submit" disabled={busy}>{busy?'جاري الحفظ...':'حفظ كلمة المرور الجديدة'}</button></form>}{message.text&&<p className={`auth-message ${message.type}`}>{message.text}</p>}<Link className="auth-back" to="/login">العودة إلى تسجيل الدخول</Link></div></div></main>;
}
